spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          time_zone: UTC
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        cdi.extensions: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    azure:
      storage:
        account-name: licentagaitacantina
        account-key: a0VpCpfFKeSaXQvMAFR8oBZGYSiPWg9IXpAh0N5Dp8cxA+dSHGy7jD0qIiuiF5yHau9+UPQpmRqY+ASttntY+Q==
        blob:
          container-name: menuimage

  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force-response: true



springdoc:
  packagesToScan: com.example.cantinabackend.web
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc
    default-models-expand-depth: -1
    tagsSorter: alpha
    operationsSorter: method

logging:
  level:
    org:
      springframework:
        security: DEBUG
