version: "3.9"
name: "cantina-backend"

services:

  db:
    container_name: cantina-db
    image: mysql:8.0.35
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${DATABASE_USER} --password=${DATABASE_PASSWORD}
      interval: 1s
      retries: 30
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: "%"
      TZ: UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=UTC

  flyway:
    container_name: cantina-flyway
    image: flyway/flyway:9.22.3
    environment:
      FLYWAY_USER: ${DATABASE_USER}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
      FLYWAY_URL: jdbc:mysql://db:3306/${DATABASE_NAME}
      FLYWAY_GROUP: true
      FLYWAY_LOCATIONS: filesystem:/flyway/sql,filesystem:/flyway/dev/sql
    command: migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql:ro
      - ./flyway/local_migrations:/flyway/dev/sql:ro
    depends_on:
      db:
        condition: service_healthy